# Generated by Django 2.2.6 on 2019-10-06 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=40)),
                ('address', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('signInDate', models.DateTimeField(default=datetime.datetime(2019, 10, 6, 15, 26, 33, 580984, tzinfo=utc))),
                ('lastLoginDate', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('name', models.TextField(default='John', max_length=30)),
                ('surname', models.TextField(default='Kennedy', max_length=30)),
                ('permissions', models.CharField(blank=True, max_length=20)),
                ('ownerID', models.ManyToManyField(blank=True, to='RestIT.Business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(to='RestIT.BusinessUser'),
        ),
    ]
