# Generated by Django 2.2.6 on 2019-10-07 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestIT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='signInDate',
        ),
        migrations.AddField(
            model_name='businessuser',
            name='signUpDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 10, 50, 22, 758782, tzinfo=utc)),
        ),
    ]
