# Generated by Django 2.2.6 on 2019-10-06 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RestIT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='signInDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 15, 27, 4, 363454, tzinfo=utc)),
        ),
    ]
